name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: echo "Hello TestBash!"
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd ./src/webapp/api && npm ci && npm run test
  start-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          cd ./src/webapp &&
          npm ci &&
          npm run start-server &
          sleep 10 &&
          curl http://localhost:8080 -I
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: start-webapp
    steps:
      - run: cd ./e2e/cypress && npm ci && npm run test