name: hello testBash
run-name: hello testBash
on: [push]
jobs:
  Run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: cd ./src/webapp/api && npm install && npm run test
  Run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: cd ./e2e/cypress && npm install && npm run test